env: "dev"

http_server:
  port: 8083
  read_timeout: 5m
  write_timeout: 5m
  idle_timeout: 60s

auth:
  bot_key: ""

pg:
  url: ""

kafka:
  broker: ""
  topics:
    logs: ""
  groups:
    user: "user-service-group"