env: "dev"

http_server:
  port: 8081
  read_timeout: 5m
  write_timeout: 5m
  idle_timeout: 60s
  allowed_origins:

auth:
  access_token_ttl: 15m
  refresh_token_ttl: 720h
  jwt_sign_key: ""
  bot_key: ""

services:
  chat_model_url: "http://chat-model:8082"
  user_service_url: "http://user-service:8083"
  docs_model_url: "http://docs_model:8084"
  recomendator_url: "http://recomendator:8085"
  summarizer_url: "http://summarizer:8086"
  business_analyzer_url: "http://business_analyzer:8087"
  defender_url: "http://defender:8088"
  conversation_service_url: "http://conversation-service:8090"
  db_service_url: "http://db_service:8093"
  email_service_url: "http://email_service:8094"
  model_service_url: "http://model-service:8095"
  speech_service_url: "http://speech-service:5096"

security:
  defender_check:
    enabled: true
