env: "dev"

http_server:
  port: 8080
  read_timeout: 5m
  write_timeout: 5m
  idle_timeout: 60s
  allowed_origins:

jwt:
  sign_key: ""
  tokenTTL: 120m

services:

prometheus:
  enabled: true
  path: /metrics