global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8081']
      
  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 15s


  - job_name: 'clickhouse_exporter'
    static_configs:
      - targets: ['clickhouse-exporter:9116']
    scrape_interval: 20s


  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 20s


  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s


  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
